### PR TITLE
biomformat

### PR DESCRIPTION
**Pull request by jnpaulson**
I didn't realize you had a vignette already! It was pretty simple to move it / rename it per BioC's criteria. We should discuss swapping out the underlying data-structure to an eSet object, but that would be more long term. In short, I think this is good after changing the repo name. Any thoughts?

### CODE REVIEW

**Comment by joey711** [comment]
Looks good. Keep in mind the current repo will need to stay in place to support the CRAN biom package unless/until it is fully retired from CRAN. We should migrate this update and changes to a brand new repo.

Thoughts on where it should live? `joey711/biomformat`? or something else?

**Comment by jnpaulson** [comment]
Right, I believe |joey711/biomformat |is the appropriate repo locale.

**Comment by joey711** [comment]
@nosson 
For various reasons, I'm trying to solve this issue today. Would love to include the short-term CRAN-only update for HDF5 biom format. Is that a branch sitting somewhere? If so I'll push to CRAN right away. Meanwhile, I should migrate this to `joey711/biomformat`. Will ping you once that is ready.

Quick question, does this recognize the format/version of the `.biom` file that a user would provide? Ideally this is opaque to the user, maybe with a tiny message so they're aware of the difference but don't do anything differently.

Cheers!
joey

**Comment by jnpaulson** [comment]
Yes, it reads the format/version of the .biom file:
https://github.com/nosson/biom/blob/master/R/IO-methods.R#L159-L161 and is
stored in the biom-class I believe?

I don't have a CRAN-only update, but will test one real quick

**Comment by jnpaulson** [comment]
Mhmm - the `h5` library is giving me way more trouble than it should be. Any other suggestions?

**Comment by joey711** [comment]
Crap. I'll look around. Weird. I would have guessed CRAN to have a general-purpose tool like this before BioC

**Comment by joey711** [comment]
I consulted this SO post:

http://stackoverflow.com/questions/15974643/how-to-deal-with-hdf5-files-in-r

Looks like there used to be an [hdf5 package on CRAN](http://cran.r-project.org/web/packages/hdf5/index.html) that has since been removed. 

There were a few examples in that SO post, but the top answer was rhdf5. Too bad.

At a minimum we can add a prelim test in this JSON-only `biom` package that determines if in fact the input file is JSON, and if not, throw an informative error message.

**Comment by joey711** [comment]
The following worked brilliantly for branch migration to new repo:

http://stackoverflow.com/questions/9527999/how-do-i-create-a-new-github-repo-from-a-branch-in-an-existing-repo

The new repo is here:

https://github.com/joey711/biomformat

@nosson is an official "pushable" contributor.

**Pull request closed without merging**
