### PR TITLE
Added matrix_element_type flag for make_biom

### PR DESCRIPTION
**Pull request by nosson**
Hey,

I hope all is well. I noticed that if there is a non-integer biom file with the matrix_element_type flag set to 'int' pieces get truncated in downstream analyses by other programs. I added a matrix_element_type flag to make_biom to allow for 'floats'. It might be best to add a test - is matrix_element_type int or float, etc?

What do you think?

### CODE REVIEW

**Comment by nosson** [comment]
Hey @joey711!

I just upgraded the biom package in a number of ways

1) R CMD check had a few issues with the aliases being used for show, ncol, nrow
2) Upgraded documentation using roxygen 2.0
3) Included hdf5 (biom-format vs 2.0) example files
4) Import from rhdf5 package to handle that type of data
5) Restructure read_biom to read in either biom vs 1 or 2 formatted data
6) Included tests for the new hdf5 data. 
7) uptick biom from 0.3.xx to 0.4.0

There are a few under the hood nuances I'd love to discuss whenever you have time, however, the priority would be to just push this now so that users of all the R packages (phyloseq, metagenomeSeq, etc) will now seamlessly grab and use them.

**Comment by joey711** [comment]
Nice. I'll run it through some tests before pushing it over to CRAN.

Looks like @nosson needs to be added to the package author list...

**Comment by joey711** [comment]
BTW, do you have any tests you can include for the hdf5 format? Some small example files?

**Comment by joey711** [comment]
Wait. There's a problem. This is currently a CRAN package, but "rhdf5" is on Bioconductor. We'd have to formally submit it there. I don't have a problem pushing up to BioC, but it means a delay and we'll need to update the GitHub-level installation doc.

What about a CRAN-side hdf5 support?

http://stackoverflow.com/questions/15974643/how-to-deal-with-hdf5-files-in-r

**Comment by nosson** [comment]
Yeah! I included the min and rich hdf5 files in `extdata` and added tests here:

https://github.com/nosson/biom/commit/143dd9f4c780e034257ae55531df9d68d3134748#diff-f4a4407718628ef90dcb63ff63771ebfR14

**Comment by nosson** [comment]
Mhmm - I can try `h5`[http://cran.r-project.org/web/packages/h5/index.html] , `ncdf`[http://cran.r-project.org/web/packages/ncdf4/index.html] and `rgdal`[http://cran.r-project.org/web/packages/rgdal/index.html] I'll get back to you soon.

**Comment by joey711** [comment]
rgdal looks squirrelly because of the binaries-not-working issue someone mentioned. Others look like they might be worth trying... but only if it's relatively quick. 

We could focus our efforts on forking and preparing this for BioC submission if it looks like the interim CRAN solution will be too much of a pain.

I like the idea of getting onto BioC... thoughts?

**Comment by nosson** [comment]
I love the idea of putting this into BioC - actually think that's the more
appropriate venue for it. To be honest, I think that it is already ready to
go to BioC once we have a vignette (I could write a minimal one on my
flight tonight if you'd like). Even if it's there, we can continually
update the devel version and the release will just flow.

**Comment by joey711** [comment]
Sounds good. Let's show an explicit installation script somewhere front and center to emphasize that they need to install a BioC dependency, and then head that route. I also think BioC is more appropriate in the long run. CRAN was faster and simpler.

I better also check with CRAN about packages that depend on this one. If there are any, we can snapshot the version that is on there, and notify the other maintainers about this switch.

**Comment by joey711** [comment]
No reverse dependencies. Only a reverse "Suggests", @kylebittinger Kyle Bittinger's [qiimer package](https://github.com/kylebittinger/qiimer).

@kylebittinger FYI, we are probably going to go ahead and fork this, switching the current CRAN "biom" package into maintenance mode so that we can add this hdf5/biom2.0 support on a Bioconductor version, also moving future maintenance/devel of the package over to there. If you want we can construct a separate forked version of this with CRAN-side support. Maybe you can pitch in on adding that there, if you want it? Is this an issue you've solved already for qiimer?

New name:
For clarity we should rename the version of this package headed to Bioconductor. Ideas: 

- Biom
- rbiom 
- biomformat
- biomio
- biomlite

Thoughts? Suggestions?

joey

**Comment by nosson** [comment]
Mhmm - no reverse dependencies in CRAN. I know metagenomeSeq suggests it. 

I like one of these:
biomformat
biomlite
rbiom

**Comment by joey711** [comment]
Okay, well, we won't change the current CRAN version, so we can leave it up to maintainers to decide. I can figure out how to send a notification to developers on both repos once we've got the BioC version in place. 

Sound good? Either way, CRAN biom package can stay in maintenance mode for some time without causing problems. Eventually I'll post some updates in the doc of the package making it clear that it is becoming a deprecated package and BioC version is where devels should point in the future.

How about biomformat?

**Comment by nosson** [comment]
biomformat sounds great :+1: 

I'll write up a minimal vignette for the submission tonight and do a pull request. Then a next 'major' development on the drawing board might be:

* `write_biom` function for vs 2 format
* incorporating the mothur biom files (though that might be on their end)
* tweaks on the inside

**Comment by joey711** [comment]
I like it. I think there's at least one issue on the phyloseq tracker about importing mothur-generated biom files...

I like it! This should be pretty quick (relatively speaking).

This will be a nice building block for the next level up "microbiomeBase" package (or whatever we're going to call it)

**Comment by kylebittinger** [comment]
Joey,

Plans for the biomformat package sound good.  I do not need a separate package on CRAN.  In fact, there are no library calls to `biom` in my code, so no real dependency.

Once you guys have the new package up, I'll suggest that to users for BIOM file import.  If it's hard to suggest a bioconductior package from CRAN, then I'll point it out prominently in the documentation.

I have only a couple utility functions in `qiimer` dealing with JSON-formatted BIOM files.  If the interface in your package makes this stuff easy, then I'll just remove those functions from my package.  Happy to have less to maintain.

I have to admit that my normal procedure is still to make a TSV file in "classic" format and import from there! I'll have to catch up with the new file formats someday, I guess. :)

Thanks for your work, look forward to using biomformat!

**Comment by joey711** [comment]
Great, thanks @kylebittinger that's helpful. Glad to know we won't brick your package by any changes O:-) ... conversely, sad to hear you're not really depending on "biom"! You're the only one! Okay, well, there are likely more growing on BioC, so I guess that's why we'll migrate over there.

Yeah, classic TSV seems fine for a lot of stuff. phyloseq uses the very fast `data.table::fread` function, which is much faster and more memory-concious than JSON handlers anyway. I like the idea of a more advanced format like hdf5, but haven't really had much of a need for it. Even for very large files, TSV still works okay, and when it starts to not work, will probably be using a database or compressed RData binaries. 

Thanks for the kind words. Will keep you posted!

**Comment by kylebittinger** [comment]
Don't be sad! It's because I coded to the interface, not the implementation.

**Pull request merged**
